before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmecab2
  - sudo apt-get install -y libmecab-dev
  - sudo apt-get install -y libmecab-util
  - sudo apt-get install -y mecab-ipadic-utf8
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
script: "python tests.py"
